services:
  engine:
    container_name: engine
    image: mini-santa:latest
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD-SHELL", "sh", "/executables/bash-scripts/healthcheck.sh"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    env_file:
      - ./.env/.basic_info
      - ./.env/.admin_info
    volumes:
      - engine-db:/executables/db:rw
    networks:
      - internal
  webserver:
    container_name: webserver
    image: caddy:2.10.2-alpine
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      engine:
        condition: service_healthy
    environment:
      CADDY_TELEMETRY: "off"
    volumes:
      - ./caddy_conf:/etc/caddy
      - caddy_data:/data:rw
      - caddy_config:/config:rw
    networks:
      - internal
      - external
    ports:
      - "80:80"
      - "443:443"
networks:
  external:
    driver: bridge
  internal:
    driver: bridge

volumes:
  engine-db: null
  caddy_data: null
  caddy_config: null